// Code generated by goyacc -p jp -o lib/json/path_parser.go -v lib/json/path_parser.output lib/json/path_parser.y. DO NOT EDIT.

//line lib/json/path_parser.y:2
package json

//line lib/json/path_parser.y:2

//line lib/json/path_parser.y:5
type jpSymType struct {
	yys        int
	expression PathExpression
	member     ObjectPath
	token      PathToken
}

const OBJECT_PATH = 57346

var jpToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"OBJECT_PATH",
	"'.'",
}

var jpStatenames = [...]string{}

const jpEofCode = 1
const jpErrCode = 2
const jpInitialStackSize = 16

//line lib/json/path_parser.y:40

func ParsePath(src string) (PathExpression, error) {
	_ = "STUB: not implemented"
	return *new(PathExpression), nil
}

//line yacctab:1
var jpExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const jpPrivate = 57344

const jpLast = 7

var jpAct = [...]int{
	4, 2, 3, 1, 0, 0, 5,
}

var jpPact = [...]int{
	-2, -1000, -1000, -5, -2, -1000,
}

var jpPgo = [...]int{
	0, 3, 1,
}

var jpR1 = [...]int{
	0, 1, 1, 2, 2,
}

var jpR2 = [...]int{
	0, 0, 1, 1, 3,
}

var jpChk = [...]int{
	-1000, -1, -2, 4, 5, -2,
}

var jpDef = [...]int{
	1, -2, 2, 3, 0, 4,
}

var jpTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 5,
}

var jpTok2 = [...]int{
	2, 3, 4,
}

var jpTok3 = [...]int{
	0,
}

var jpErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	jpDebug        = 0
	jpErrorVerbose = false
)

type jpLexer interface {
	Lex(lval *jpSymType) int
	Error(s string)
}

type jpParser interface {
	Parse(jpLexer) int
	Lookahead() int
}

type jpParserImpl struct {
	lval  jpSymType
	stack [jpInitialStackSize]jpSymType
	char  int
}

func (p *jpParserImpl) Lookahead() int { _ = "STUB: not implemented"; return 0 }

func jpNewParser() jpParser { _ = "STUB: not implemented"; return *new(jpParser) }

const jpFlag = -1000

func jpTokname(c int) string { _ = "STUB: not implemented"; return "" }

func jpStatname(s int) string { _ = "STUB: not implemented"; return "" }

func jpErrorMessage(state, lookAhead int) string { _ = "STUB: not implemented"; return "" }

// To match Bison, suggest at most four expected tokens.

// Look for shiftable tokens.

// Look for tokens that we accept or reduce.

// If the default action is to accept or reduce, give up.

func jplex1(lex jpLexer, lval *jpSymType) (char, token int) { _ = "STUB: not implemented"; return 0, 0 }

/* unknown char */

func jpParse(jplex jpLexer) int { _ = "STUB: not implemented"; return 0 }

func (jprcvr *jpParserImpl) Parse(jplex jpLexer) int { _ = "STUB: not implemented"; return 0 }

// silence set and not used

/* number of errors */
/* error recovery flag */

// jprcvr.char translated into internal numbering

// Make sure we report no lookahead when not parsing.

/* put a state and value onto the stack */

/* simple state */

/* valid shift */

/* default state action */

/* look through exception table */

/* error ... attempt to resume parsing */

/* brand new error */

/* incompletely recovered error ... try again */

/* find a state where "error" is a legal shift action */

/* simulate a shift of "error" */

/* the current p has no shift on "error", pop stack */

/* there is no state on the stack with an error shift ... abort */

/* no shift yet; clobber input char */

/* try again in the same state */

/* reduction by production jpn */

// guard against "declared and not used"

// jpp is now the index of $0. Perform the default action. Iff the
// reduced production is ε, $1 is possibly out of range.

/* consult goto table to find next state */

// dummy call; replaced with literal code

//line lib/json/path_parser.y:20

//line lib/json/path_parser.y:25

//line lib/json/path_parser.y:32

//line lib/json/path_parser.y:36

/* stack new state and value */
