// Code generated by goyacc -p jq -o lib/json/query_parser.go -v lib/json/query_parser.output lib/json/query_parser.y. DO NOT EDIT.

//line lib/json/query_parser.y:2
package json

//line lib/json/query_parser.y:2

//line lib/json/query_parser.y:7
type jqSymType struct {
	yys        int
	expression QueryExpression
	element    Element
	field      FieldExpr
	fields     []FieldExpr
	token      QueryToken
}

const PATH_IDENTIFIER = 57346
const PATH_INDEX = 57347
const AS = 57348

var jqToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"PATH_IDENTIFIER",
	"PATH_INDEX",
	"AS",
	"'.'",
	"'['",
	"']'",
	"'{'",
	"'}'",
	"','",
}

var jqStatenames = [...]string{}

const jqEofCode = 1
const jqErrCode = 2
const jqInitialStackSize = 16

//line lib/json/query_parser.y:185

func ParseQuery(src string) (QueryExpression, error) {
	_ = "STUB: not implemented"
	return *new(QueryExpression), nil
}

//line yacctab:1
var jqExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const jqPrivate = 57344

const jqLast = 50

var jqAct = [...]int{
	18, 3, 23, 16, 26, 6, 5, 30, 8, 4,
	9, 40, 20, 13, 12, 10, 8, 11, 9, 27,
	7, 25, 29, 34, 8, 35, 9, 33, 32, 38,
	36, 31, 39, 14, 41, 24, 19, 15, 28, 24,
	22, 24, 43, 42, 21, 7, 37, 17, 2, 1,
}

var jqPact = [...]int{
	16, -1000, -1000, -1000, -1000, -1000, -1000, 8, 28, 32,
	41, -1000, -1000, -1000, 35, 33, 10, -8, 13, 31,
	-1000, 0, 32, -1000, 20, -1000, 32, 42, 32, -1000,
	41, -1000, -1000, -1000, -1000, 2, -1000, -1000, -1000, -1000,
	27, 32, -1000, -1000,
}

var jqPgo = [...]int{
	0, 49, 48, 1, 0, 9, 2, 6, 5, 47,
	3,
}

var jqR1 = [...]int{
	0, 1, 1, 2, 2, 2, 2, 3, 3, 3,
	3, 3, 4, 4, 4, 5, 5, 5, 5, 5,
	6, 6, 6, 7, 7, 7, 8, 9, 9, 10,
	10, 10,
}

var jqR2 = [...]int{
	0, 0, 1, 1, 1, 1, 1, 1, 3, 2,
	2, 2, 1, 3, 2, 3, 5, 4, 4, 4,
	3, 5, 4, 2, 4, 3, 3, 1, 3, 0,
	1, 3,
}

var jqChk = [...]int{
	-1000, -1, -2, -3, -5, -7, -8, 4, 8, 10,
	7, -5, -7, -8, 5, 9, -10, -9, -4, 4,
	-3, 9, 7, -6, 8, 11, 12, 6, 7, -6,
	7, -5, -7, -8, -4, 5, -10, 4, -4, -3,
	9, 7, -6, -4,
}

var jqDef = [...]int{
	1, -2, 2, 3, 4, 5, 6, 7, 0, 29,
	0, 9, 10, 11, 0, 23, 0, 30, 27, 12,
	8, 15, 0, 25, 0, 26, 29, 0, 0, 14,
	0, 17, 18, 19, 24, 0, 31, 28, 13, 16,
	20, 0, 22, 21,
}

var jqTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 12, 3, 7, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 8, 3, 9, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 10, 3, 11,
}

var jqTok2 = [...]int{
	2, 3, 4, 5, 6,
}

var jqTok3 = [...]int{
	0,
}

var jqErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	jqDebug        = 0
	jqErrorVerbose = false
)

type jqLexer interface {
	Lex(lval *jqSymType) int
	Error(s string)
}

type jqParser interface {
	Parse(jqLexer) int
	Lookahead() int
}

type jqParserImpl struct {
	lval  jqSymType
	stack [jqInitialStackSize]jqSymType
	char  int
}

func (p *jqParserImpl) Lookahead() int { _ = "STUB: not implemented"; return 0 }

func jqNewParser() jqParser { _ = "STUB: not implemented"; return *new(jqParser) }

const jqFlag = -1000

func jqTokname(c int) string { _ = "STUB: not implemented"; return "" }

func jqStatname(s int) string { _ = "STUB: not implemented"; return "" }

func jqErrorMessage(state, lookAhead int) string { _ = "STUB: not implemented"; return "" }

// To match Bison, suggest at most four expected tokens.

// Look for shiftable tokens.

// Look for tokens that we accept or reduce.

// If the default action is to accept or reduce, give up.

func jqlex1(lex jqLexer, lval *jqSymType) (char, token int) { _ = "STUB: not implemented"; return 0, 0 }

/* unknown char */

func jqParse(jqlex jqLexer) int { _ = "STUB: not implemented"; return 0 }

func (jqrcvr *jqParserImpl) Parse(jqlex jqLexer) int { _ = "STUB: not implemented"; return 0 }

// silence set and not used

/* number of errors */
/* error recovery flag */

// jqrcvr.char translated into internal numbering

// Make sure we report no lookahead when not parsing.

/* put a state and value onto the stack */

/* simple state */

/* valid shift */

/* default state action */

/* look through exception table */

/* error ... attempt to resume parsing */

/* brand new error */

/* incompletely recovered error ... try again */

/* find a state where "error" is a legal shift action */

/* simulate a shift of "error" */

/* the current p has no shift on "error", pop stack */

/* there is no state on the stack with an error shift ... abort */

/* no shift yet; clobber input char */

/* try again in the same state */

/* reduction by production jqn */

// guard against "declared and not used"

// jqp is now the index of $0. Perform the default action. Iff the
// reduced production is ε, $1 is possibly out of range.

/* consult goto table to find next state */

// dummy call; replaced with literal code

//line lib/json/query_parser.y:33

//line lib/json/query_parser.y:38

//line lib/json/query_parser.y:45

//line lib/json/query_parser.y:49

//line lib/json/query_parser.y:53

//line lib/json/query_parser.y:57

//line lib/json/query_parser.y:63

//line lib/json/query_parser.y:67

//line lib/json/query_parser.y:71

//line lib/json/query_parser.y:75

//line lib/json/query_parser.y:79

//line lib/json/query_parser.y:85

//line lib/json/query_parser.y:89

//line lib/json/query_parser.y:93

//line lib/json/query_parser.y:99

//line lib/json/query_parser.y:104

//line lib/json/query_parser.y:109

//line lib/json/query_parser.y:114

//line lib/json/query_parser.y:119

//line lib/json/query_parser.y:126

//line lib/json/query_parser.y:131

//line lib/json/query_parser.y:136

//line lib/json/query_parser.y:143

//line lib/json/query_parser.y:147

//line lib/json/query_parser.y:151

//line lib/json/query_parser.y:157

//line lib/json/query_parser.y:163

//line lib/json/query_parser.y:167

//line lib/json/query_parser.y:173

//line lib/json/query_parser.y:177

//line lib/json/query_parser.y:181

/* stack new state and value */
